=== stefanjank22/ist2021/proizvodi.dtd
<!ELEMENT proizvodi (proizvod+)>
<!ELEMENT proizvod (kategorija, cena, tekstOglasa, oznake, akcije)>
<!ELEMENT kategorija EMPTY>
<!ELEMENT cena (#PCDATA)>
<!ELEMENT tekstOglasa (#PCDATA)>
<!ELEMENT oznake (oznaka*)>
<!ELEMENT oznaka (#PCDATA)>
<!ELEMENT akcije (akcija*)>
<!ELEMENT akcija EMPTY>
<!ATTLIST kategorija naziv (pc | laptop | mobilni) #REQUIRED>
<!ATTLIST cena valuta (rsd) "rsd">
<!ATTLIST akcija cena CDATA #REQUIRED>
<!ATTLIST akcija datumIsteka CDATA #REQUIRED>

=== stefanjank22/ist2021/proizvodi.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE proizvodi SYSTEM "proizvodi.dtd">
<proizvodi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="proizvodi.xsd">
  <proizvod>
    <kategorija naziv="laptop"></kategorija>
    <cena valuta="rsd">90000</cena>
    <tekstOglasa>Neki tekst ogalsa</tekstOglasa>
    <oznake>
      <oznaka>akcija</oznaka>
    </oznake>
    <akcije>
      <akcija cena="80000" datumIsteka="2021-09-01"></akcija>
    </akcije>
  </proizvod>
</proizvodi>
